apiVersion: ovs.openstack.org/v1beta1
kind: OVS
metadata:
  name: openvswitch
spec:
  ovsContainerImage: "quay.io/skaplons/ovs:latest"
  ovnContainerImage: "quay.io/tripleowallaby/openstack-ovn-controller:current-tripleo"
  external-ids:
    system-id: "random"
    ovn-bridge: "br-int"
    ovn-encap-type: "geneve,vxlan"
  nic_mappings:
    physnet2: enp2s0.100
    physnet3: enp2s0.200
  tunnelNetworkCidr: 10.20.30.40/24
  tunnelNetworkNic: enp2s0.300
